/**
 * countryConfig.js
 * Ek hi jagah par har desh ka fark. Form ke andar `country === 'India'`
 * jaisi condition likhne ki zaroorat nahi — sirf yahan se config uthao.
 *
 * Usage:
 *   import { getCountryConfig, COUNTRY_OPTIONS } from '../../../Config/countryConfig';
 *   const cfg = getCountryConfig(country);
 *
 * 50 desh — Jain samaj ki maujoodgi ke hisaab se.
 */

export const COUNTRY_CONFIG = {
  India: {
    iso: "IN",
    dialCode: "+91",
    phoneLength: [10],
    currency: "INR",
    currencySymbol: "₹",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region2Label: "District",
    region2Required: true,
    hasStateDropdown: true,
    postal: {
      label: "PIN Code",
      required: true,
      keyboard: "number-pad",
      maxLength: 6,
      regex: /^[1-9][0-9]{5}$/i,
      placeholder: "452001",
    },
  },
  "United States": {
    iso: "US",
    dialCode: "+1",
    phoneLength: [10],
    currency: "USD",
    currencySymbol: "$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region1FieldName: "state",
    region2Label: "County",
    region2FieldName: "county",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "ZIP Code",
      fieldName: "zip_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 10,
      regex: /^\d{5}(-\d{4})?$/i,
      placeholder: "07430",
    },
  },
  "United Kingdom": {
    iso: "GB",
    dialCode: "+44",
    phoneLength: [10, 11],
    currency: "GBP",
    currencySymbol: "£",
    dateFormat: "DD/MM/YYYY",
    region1Label: "County",
    region1FieldName: "county",
    region2Label: "Town / Borough",
    region2FieldName: "town_borough",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postcode",
      fieldName: "postcode",
      required: true,
      keyboard: "default",
      maxLength: 8,
      regex: /^[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}$/i,
      placeholder: "EN6 1TL",
      uppercase: true,
    },
  },
  Canada: {
    iso: "CA",
    dialCode: "+1",
    phoneLength: [10],
    currency: "CAD",
    currencySymbol: "C$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "Region",
    region2FieldName: "region",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "default",
      maxLength: 7,
      regex: /^[A-Z]\d[A-Z]\s?\d[A-Z]\d$/i,
      placeholder: "M5V 3L9",
      uppercase: true,
    },
  },
  Australia: {
    iso: "AU",
    dialCode: "+61",
    phoneLength: [9],
    currency: "AUD",
    currencySymbol: "A$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State / Territory",
    region1FieldName: "state_territory",
    region2Label: "Suburb",
    region2FieldName: "suburb",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postcode",
      fieldName: "postcode",
      required: true,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "3000",
    },
  },
  "New Zealand": {
    iso: "NZ",
    dialCode: "+64",
    phoneLength: [8, 9],
    currency: "NZD",
    currencySymbol: "NZ$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postcode",
      fieldName: "postcode",
      required: true,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "1010",
    },
  },
  Kenya: {
    iso: "KE",
    dialCode: "+254",
    phoneLength: [9],
    currency: "KES",
    currencySymbol: "KSh",
    dateFormat: "DD/MM/YYYY",
    region1Label: "County",
    region1FieldName: "county",
    region2Label: "Sub-County",
    region2FieldName: "subcounty",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "00100",
    },
  },
  Tanzania: {
    iso: "TZ",
    dialCode: "+255",
    phoneLength: [9],
    currency: "TZS",
    currencySymbol: "TSh",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "11101",
    },
  },
  Uganda: {
    iso: "UG",
    dialCode: "+256",
    phoneLength: [9],
    currency: "UGX",
    currencySymbol: "USh",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Zambia: {
    iso: "ZM",
    dialCode: "+260",
    phoneLength: [9],
    currency: "ZMW",
    currencySymbol: "K",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "10101",
    },
  },
  Zimbabwe: {
    iso: "ZW",
    dialCode: "+263",
    phoneLength: [9],
    currency: "USD",
    currencySymbol: "$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Malawi: {
    iso: "MW",
    dialCode: "+265",
    phoneLength: [9],
    currency: "MWK",
    currencySymbol: "MK",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Mozambique: {
    iso: "MZ",
    dialCode: "+258",
    phoneLength: [9],
    currency: "MZN",
    currencySymbol: "MT",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "1100",
    },
  },
  Nigeria: {
    iso: "NG",
    dialCode: "+234",
    phoneLength: [10],
    currency: "NGN",
    currencySymbol: "₦",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region1FieldName: "state",
    region2Label: "LGA",
    region2FieldName: "lga",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 6,
      regex: /^\d{6}$/i,
      placeholder: "100001",
    },
  },
  Madagascar: {
    iso: "MG",
    dialCode: "+261",
    phoneLength: [9],
    currency: "MGA",
    currencySymbol: "Ar",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 3,
      regex: /^\d{3}$/i,
      placeholder: "101",
    },
  },
  "South Africa": {
    iso: "ZA",
    dialCode: "+27",
    phoneLength: [9],
    currency: "ZAR",
    currencySymbol: "R",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "2196",
    },
  },
  Botswana: {
    iso: "BW",
    dialCode: "+267",
    phoneLength: [8],
    currency: "BWP",
    currencySymbol: "P",
    dateFormat: "DD/MM/YYYY",
    region1Label: "District",
    region1FieldName: "district",
    region2Label: "Sub-District",
    region2FieldName: "subdistrict",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Mauritius: {
    iso: "MU",
    dialCode: "+230",
    phoneLength: [8],
    currency: "MUR",
    currencySymbol: "₨",
    dateFormat: "DD/MM/YYYY",
    region1Label: "District",
    region1FieldName: "district",
    region2Label: "Town / Village",
    region2FieldName: "town_or_village",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "default",
      maxLength: 6,
      regex: null,
      placeholder: "",
      uppercase: true,
    },
  },
  "United Arab Emirates": {
    iso: "AE",
    dialCode: "+971",
    phoneLength: [9],
    currency: "AED",
    currencySymbol: "AED",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Emirate",
    region1FieldName: "emirate",
    region2Label: "Area",
    region2FieldName: "area",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Qatar: {
    iso: "QA",
    dialCode: "+974",
    phoneLength: [8],
    currency: "QAR",
    currencySymbol: "QAR",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Municipality",
    region1FieldName: "municipality",
    region2Label: "Zone",
    region2FieldName: "zone",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Bahrain: {
    iso: "BH",
    dialCode: "+973",
    phoneLength: [8],
    currency: "BHD",
    currencySymbol: "BHD",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Governorate",
    region1FieldName: "governorate",
    region2Label: "Area",
    region2FieldName: "area",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Kuwait: {
    iso: "KW",
    dialCode: "+965",
    phoneLength: [8],
    currency: "KWD",
    currencySymbol: "KWD",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Governorate",
    region1FieldName: "governorate",
    region2Label: "Area",
    region2FieldName: "area",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "13001",
    },
  },
  "Saudi Arabia": {
    iso: "SA",
    dialCode: "+966",
    phoneLength: [9],
    currency: "SAR",
    currencySymbol: "SAR",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "City",
    region2FieldName: "city",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "11564",
    },
  },
  Oman: {
    iso: "OM",
    dialCode: "+968",
    phoneLength: [8],
    currency: "OMR",
    currencySymbol: "OMR",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Governorate",
    region1FieldName: "governorate",
    region2Label: "Wilayat",
    region2FieldName: "wilayat",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 3,
      regex: /^\d{3}$/i,
      placeholder: "100",
    },
  },
  Israel: {
    iso: "IL",
    dialCode: "+972",
    phoneLength: [9],
    currency: "ILS",
    currencySymbol: "₪",
    dateFormat: "DD/MM/YYYY",
    region1Label: "District",
    region1FieldName: "district",
    region2Label: "City",
    region2FieldName: "city",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 7,
      regex: /^\d{7}$/i,
      placeholder: "5252001",
    },
  },
  Nepal: {
    iso: "NP",
    dialCode: "+977",
    phoneLength: [10],
    currency: "NPR",
    currencySymbol: "रू",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "44600",
    },
  },
  "Sri Lanka": {
    iso: "LK",
    dialCode: "+94",
    phoneLength: [9],
    currency: "LKR",
    currencySymbol: "Rs",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "00100",
    },
  },
  Bangladesh: {
    iso: "BD",
    dialCode: "+880",
    phoneLength: [10],
    currency: "BDT",
    currencySymbol: "৳",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Division",
    region1FieldName: "division",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "1000",
    },
  },
  Myanmar: {
    iso: "MM",
    dialCode: "+95",
    phoneLength: [8, 9, 10],
    currency: "MMK",
    currencySymbol: "K",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State / Region",
    region1FieldName: "state_or_region",
    region2Label: "Township",
    region2FieldName: "township",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "11181",
    },
  },
  Thailand: {
    iso: "TH",
    dialCode: "+66",
    phoneLength: [9],
    currency: "THB",
    currencySymbol: "฿",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "10500",
    },
  },
  Malaysia: {
    iso: "MY",
    dialCode: "+60",
    phoneLength: [9, 10],
    currency: "MYR",
    currencySymbol: "RM",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region1FieldName: "state",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postcode",
      fieldName: "postcode",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "50450",
    },
  },
  Singapore: {
    iso: "SG",
    dialCode: "+65",
    phoneLength: [8],
    currency: "SGD",
    currencySymbol: "S$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 6,
      regex: /^\d{6}$/i,
      placeholder: "238823",
    },
  },
  Indonesia: {
    iso: "ID",
    dialCode: "+62",
    phoneLength: [9, 10, 11],
    currency: "IDR",
    currencySymbol: "Rp",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "Regency",
    region2FieldName: "regency",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "10110",
    },
  },
  Philippines: {
    iso: "PH",
    dialCode: "+63",
    phoneLength: [10],
    currency: "PHP",
    currencySymbol: "₱",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "City / Municipality",
    region2FieldName: "city_or_municipality",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "ZIP Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "1000",
    },
  },
  Vietnam: {
    iso: "VN",
    dialCode: "+84",
    phoneLength: [9],
    currency: "VND",
    currencySymbol: "₫",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 6,
      regex: /^\d{6}$/i,
      placeholder: "100000",
    },
  },
  "Hong Kong": {
    iso: "HK",
    dialCode: "+852",
    phoneLength: [8],
    currency: "HKD",
    currencySymbol: "HK$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: null,
  },
  Japan: {
    iso: "JP",
    dialCode: "+81",
    phoneLength: [10],
    currency: "JPY",
    currencySymbol: "¥",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Prefecture",
    region1FieldName: "prefecture",
    region2Label: "City",
    region2FieldName: "city",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "default",
      maxLength: 8,
      regex: /^\d{3}-?\d{4}$/i,
      placeholder: "100-0001",
    },
  },
  Belgium: {
    iso: "BE",
    dialCode: "+32",
    phoneLength: [9],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "Commune",
    region2FieldName: "commune",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "2610",
    },
  },
  Netherlands: {
    iso: "NL",
    dialCode: "+31",
    phoneLength: [9],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "Municipality",
    region2FieldName: "municipality",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postcode",
      fieldName: "postcode",
      required: true,
      keyboard: "default",
      maxLength: 7,
      regex: /^\d{4}\s?[A-Z]{2}$/i,
      placeholder: "1012 AB",
      uppercase: true,
    },
  },
  Germany: {
    iso: "DE",
    dialCode: "+49",
    phoneLength: [10, 11],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region1FieldName: "state",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "10115",
    },
  },
  France: {
    iso: "FR",
    dialCode: "+33",
    phoneLength: [9],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "Department",
    region2FieldName: "department",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "75001",
    },
  },
  Italy: {
    iso: "IT",
    dialCode: "+39",
    phoneLength: [9, 10],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Region",
    region1FieldName: "region",
    region2Label: "Province",
    region2FieldName: "province",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "CAP",
      fieldName: "cap",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "00100",
    },
  },
  Spain: {
    iso: "ES",
    dialCode: "+34",
    phoneLength: [9],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Autonomous Community",
    region1FieldName: "autonomous_community",
    region2Label: "Province",
    region2FieldName: "province",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "28001",
    },
  },
  Austria: {
    iso: "AT",
    dialCode: "+43",
    phoneLength: [10, 11],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region1FieldName: "state",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "1010",
    },
  },
  Ireland: {
    iso: "IE",
    dialCode: "+353",
    phoneLength: [9],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "DD/MM/YYYY",
    region1Label: "County",
    region1FieldName: "county",
    region2Label: "Town",
    region2FieldName: "town",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Eircode",
      fieldName: "eircode",
      required: false,
      keyboard: "default",
      maxLength: 8,
      regex: /^[A-Z]\d{2}\s?[A-Z0-9]{4}$/i,
      placeholder: "D02 AF30",
      uppercase: true,
    },
  },
  Switzerland: {
    iso: "CH",
    dialCode: "+41",
    phoneLength: [9],
    currency: "CHF",
    currencySymbol: "CHF",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Canton",
    region1FieldName: "canton",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "8001",
    },
  },
  Sweden: {
    iso: "SE",
    dialCode: "+46",
    phoneLength: [9],
    currency: "SEK",
    currencySymbol: "kr",
    dateFormat: "DD/MM/YYYY",
    region1Label: "County",
    region1FieldName: "county",
    region2Label: "Municipality",
    region2FieldName: "municipality",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "default",
      maxLength: 6,
      regex: /^\d{3}\s?\d{2}$/i,
      placeholder: "111 22",
    },
  },
  Mexico: {
    iso: "MX",
    dialCode: "+52",
    phoneLength: [10],
    currency: "MXN",
    currencySymbol: "Mex$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region1FieldName: "state",
    region2Label: "Municipality",
    region2FieldName: "municipality",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: true,
      keyboard: "number-pad",
      maxLength: 5,
      regex: /^\d{5}$/i,
      placeholder: "01000",
    },
  },
  Brazil: {
    iso: "BR",
    dialCode: "+55",
    phoneLength: [10, 11],
    currency: "BRL",
    currencySymbol: "R$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "State",
    region1FieldName: "state",
    region2Label: "Municipality",
    region2FieldName: "municipality",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "CEP",
      fieldName: "cep",
      required: true,
      keyboard: "default",
      maxLength: 9,
      regex: /^\d{5}-?\d{3}$/i,
      placeholder: "01310-100",
    },
  },
  Panama: {
    iso: "PA",
    dialCode: "+507",
    phoneLength: [8],
    currency: "USD",
    currencySymbol: "$",
    dateFormat: "DD/MM/YYYY",
    region1Label: "Province",
    region1FieldName: "province",
    region2Label: "District",
    region2FieldName: "district",
    region2Required: false,
    hasStateDropdown: false,
    postal: {
      label: "Postal Code",
      fieldName: "postal_code",
      required: false,
      keyboard: "number-pad",
      maxLength: 4,
      regex: /^\d{4}$/i,
      placeholder: "0801",
    },
  },
};

// ---------------------------------------------------------------------------
// Fallback — list me na ho to bhi form na toote
// ---------------------------------------------------------------------------
export const DEFAULT_COUNTRY_CONFIG = {
  iso: "IN",
  dialCode: "+",
  phoneLength: [7, 8, 9, 10, 11, 12],
  currency: "USD",
  currencySymbol: "",
  dateFormat: "DD/MM/YYYY",
  region1Label: "State / Province",
  region2Label: "District / Region",
  region2Required: false,
  hasStateDropdown: false,
  postal: {
    label: "Postal Code",
    required: false,
    keyboard: "default",
    maxLength: 12,
    regex: null,
    placeholder: "",
  },
};

export const getCountryConfig = (countryName) =>
  COUNTRY_CONFIG[countryName] || DEFAULT_COUNTRY_CONFIG;

// Dropdown ke liye — India sabse upar, baaki A-Z
export const COUNTRY_OPTIONS = [
  { label: "India", value: "India" },
  ...Object.keys(COUNTRY_CONFIG)
    .filter((c) => c !== "India")
    .sort()
    .map((c) => ({ label: c, value: c })),
];

// ---------------------------------------------------------------------------
// Validators
// ---------------------------------------------------------------------------

/** Phone: sirf digits, desh ke hisaab se lambai */
export const validatePhone = (countryName, rawNumber) => {
  const cfg = getCountryConfig(countryName);
  const digits = String(rawNumber || "").replace(/\D/g, "");
  if (!digits) return { valid: false, message: "Mobile number is required" };
  if (!cfg.phoneLength.includes(digits.length)) {
    const expected = cfg.phoneLength.join(" or ");
    return {
      valid: false,
      message: `${countryName} number must be ${expected} digits`,
    };
  }
  return { valid: true, e164: `${cfg.dialCode}${digits}` };
};

/** Postal: null ho to skip, optional ho to khaali chalega */
export const validatePostal = (countryName, value) => {
  const cfg = getCountryConfig(countryName);
  if (!cfg.postal) return { valid: true }; // Uganda, UAE, Qatar waghera
  const v = String(value || "").trim();
  if (!v) {
    return cfg.postal.required
      ? { valid: false, message: `${cfg.postal.label} is required` }
      : { valid: true };
  }
  if (cfg.postal.regex && !cfg.postal.regex.test(v)) {
    return { valid: false, message: `Invalid ${cfg.postal.label}` };
  }
  return { valid: true };
};

/** Income label — "Annual Income (₹)" / "(£)" waghera */
export const incomeLabel = (countryName, base = "Annual Income") => {
  const cfg = getCountryConfig(countryName);
  return cfg.currencySymbol ? `${base} (${cfg.currencySymbol})` : base;
};
